### ISSUE TITLE
Nested static file not proxied

### ISSUE THREAD

**Issue by darbio** [architect/deploy#104]
I have a simple arc project which serves a (built) react app from public. This is then moved to the public folder and served by arc. The arc config file uses the cdn and static pragmas, with fingerprint set to true. 

When I run locally in sandbox the app works as expected. 

When I deploy to AWS the files are fingerprinted and listed in static.json, however files in subfolders aren’t served, and the arc lambda is called, resulting in a 404 key not found exception. 

E.g.
https://d273vmreiuclv3.cloudfront.net/

Works:
https://d273vmreiuclv3.cloudfront.net/static/js/runtime-main.2515dac7-0f21be98ef.js

Does not work (should work given the contents of static.json):
https://d273vmreiuclv3.cloudfront.net/static/js/runtime-main.2515dac7.js

Static.json:
```
{
  "asset-manifest.json": "asset-manifest-04efd81c20.json",
  "favicon.ico": "favicon-94cda0ace1.ico",
  "index.html": "index-077e241e89.html",
  "logo192.png": "logo192-d2533f5feb.png",
  "logo512.png": "logo512-cc5eb1d504.png",
  "manifest.json": "manifest-4e0afe7f81.json",
  "precache-manifest.a2578650294a142b23db233fcf8fa8db.js": "precache-manifest.a2578650294a142b23db233fcf8fa8db-d0c681ed8e.js",
  "robots.txt": "robots-e32f46a57d.txt",
  "service-worker.js": "service-worker-f46578894c.js",
  "static/css/main.b0551676.chunk.css": "static/css/main.b0551676.chunk-e9c6877cd6.css",
  "static/css/main.b0551676.chunk.css.map": "static/css/main.b0551676.chunk.css-31f9233d25.map",
  "static/js/2.e7958ea3.chunk.js": "static/js/2.e7958ea3.chunk-2fcf7bc254.js",
  "static/js/2.e7958ea3.chunk.js.LICENSE": "static/js/2.e7958ea3.chunk.js-4ecece6d07.LICENSE",
  "static/js/2.e7958ea3.chunk.js.map": "static/js/2.e7958ea3.chunk.js-0517fd3551.map",
  "static/js/main.4976d4f4.chunk.js": "static/js/main.4976d4f4.chunk-1a7e16b455.js",
  "static/js/main.4976d4f4.chunk.js.map": "static/js/main.4976d4f4.chunk.js-3fef2013bb.map",
  "static/js/runtime-main.2515dac7.js": "static/js/runtime-main.2515dac7-0f21be98ef.js",
  "static/js/runtime-main.2515dac7.js.map": "static/js/runtime-main.2515dac7.js-72ce635779.map"
} 
```

https://d273vmreiuclv3.cloudfront.net/static.json

Am I missing something? How do I get the routing to serve static files from sub folders?

**Comment by darbio** [comment]
[React production builds have a hash built into the names of some of the files](https://create-react-app.dev/docs/production-build/), which works around the issue for now, however I would still like to get fingerprinting working if you guys have any pointers.

**Comment by brianleroux** [comment]
hmmm. not sure why this would be but if you have fingerprinting from your react build step you should be ok! cc @ryanblock for any fingerprinting insights!

**Comment by ryanblock** [comment]
Sorry, I missed this traveling!

> Does not work (should work given the contents of static.json):

I don't think there's an issue here. `static.json` is a hash table where the property name is the filename on the local filesystem, and the value is the filename that's actually on S3/publicly available. So `runtime-main.2515dac7.js` should not work, while `runtime-main.2515dac7-0f21be98ef.js` should work.

It appears these files are being double-fingerprinted though, first by React, then by us. I'd suggest removing `fingerprint true` from your Architect project manifest and just letting React handle the fingerprinting (unless I'm missing something here!).

**Comment by darbio** [comment]
Yeah React fingerprints definitely work around the issue so it’s not a showstopper but it is definitely an issue which could cause a headache for others down the track.

**Comment by ryanblock** [comment]
I'm not sure I follow, what is the issue exactly?

**Comment by darbio** [comment]
Files in sub folders don’t appear to be served when they are fingerprinted.

**Comment by ryanblock** [comment]
Above you demonstrated that files in subfolders deliver when fingerprinted:

> Works:
> https://d273vmreiuclv3.cloudfront.net/static/js/runtime-main.2515dac7-0f21be98ef.js

> Does not work (should work given the contents of static.json):
> https://d273vmreiuclv3.cloudfront.net/static/js/runtime-main.2515dac7.js

The subfolder was `static/js/` and the (double-)fingerprinted file `runtime-main.2515dac7-0f21be98ef.js` was delivered out of that path.

I'm sorry, I feel like I'm still missing something here. But jic I'm not, a quick refresher:

Prior to deploy, Architect looks inside your `@static` folder (usually `public/`) and, if fingerprinting is enabled, upon deploy it saves each file (and its respective folder hierarchy), but with a fingerprint prepended before the file extension.

Can you explain what you expected to happen, what happened, and how it differed from what you expected to happen?

**Comment by darbio** [comment]
Absolutely! Maybe I misunderstood, so this is my expectation:

* When `@fingerprint` is set, the files are appended with a fingerprint string.
* A `static.json` file is created which is a manifest of the files that were finger printed.
* Requests to the s3 bucket on the original file name (e.g. `index.html`) resolve to a finger printed file location.

As an example:

GET `https://d273vmreiuclv3.cloudfront.net/static/js/runtime-main.2515dac7.js` should resolve to `https://d273vmreiuclv3.cloudfront.net/static/js/runtime-main.2515dac7-0f21be98ef.js`.

And another:

GET `https://d273vmreiuclv3.cloudfront.net/static/index.html` should resolve to `https://d273vmreiuclv3.cloudfront.net/static/index-077e241e89.html`

This seems to work for the second example (index.html) but not for the first (js/runtime-main.2515dac7.js).

**Comment by ryanblock** [comment]
Ah, ok, there's the problem – possibly poor documentation on our side!

> Requests to the s3 bucket on the original file name (e.g. index.html) resolve to a finger printed file location.

I'm not sure what you mean by resolve (301/302?), but S3 and the CDN delivers the files requested, so what you mentioned does not occur.

If I may, you wouldn't want that anyway, since it would at least partially defeat the purpose – to build the fastest sites, you want to minimize HTTP roundtrips, so ideally you'd have a single HTTP request to a completely unique filename. One and done.

The `static.json` file is there so your code has awareness of the final fingerprinted filenames that are now live on your CDN.

For example, in Node you could do `arc.static('foo/index.png')` and that would automatically resolve to  `foo/index-abc123.png').

Given the example static.json above I don't see how the former example wouldn't work, but the latter would. How were you attempting to use the fingerprinted names?

> Maybe I am over-estimating what the framework does, but I was under the impression that it will resolve file names using static.json (and FWIW I think the double-fingerprint shouldn't make a difference). Did I miss something here?

Well, per above, I think that just depends on **how** you're expecting that to fingerprint resolving to occur. If you're expecting automagical file-forwarding, Architect (and afaik S3) don't do that, but if you're using `arc.static` (or something similar of your own making) you _should_ be good.

For reference, here's the static resolver (dumb as a bag of 🔨s): https://github.com/architect/functions/blob/master/src/static/index.js#L23-L27

Anyway, back to my question above: what technique(s) were you attempting to make use of the fingerprinted URLs?

**Comment by darbio** [comment]
I was attempting to host a built React app (contents of `dist` in create-react-app) using the `public` folder in my architect project. It worked for the `index.html` file (I assume that this is because this is served through a handler?) but then when the app tries to load the rest of it's contents (e.g. `js/**.js` files) it falls over because it can't resolve the dependency.

**Comment by ryanblock** [comment]
Ok got it, I'm on the same page now. Architect has its own fingerprinting because we've seen a lot of people get bitten by NOT having it – but those are mostly the folks who are using tools that don't have fingerprinting built right in.

So your solution here is: disable Architect's fingerprinting so long as you've got fingerprinting from React (or whatever other f/e framework you're using). You shouldn't need Architect's fingerprinting because React is handling that for you – that is, unless disabling is somehow detrimental or breaking something. (Is it?)

Otherwise, if/when you do need Architect's own fingerprinting aside from React's, use `arc.static` (or something similar to it that you make yourself) and you should be good to go.

wdyt?
